<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251202120227 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE donneur_m (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_cristal INT NOT NULL, groupe_sanguin VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE donneur_v (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_cristal INT NOT NULL, groupe_sanguin VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, num_dossier INT NOT NULL, PRIMARY KEY (id))');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE donneur_m');
        $this->addSql('DROP TABLE donneur_v');
        $this->addSql('DROP TABLE patient');

    }
}
