<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251208075843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chirurgien (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE donneur_m (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_cristal INT NOT NULL, groupe_sanguin VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE donneur_v (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_cristal INT NOT NULL, groupe_sanguin VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE greffe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fonctionnel BOOLEAN NOT NULL, date_fin_de_fonction TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, type VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE groupage_hla (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hla_a INT NOT NULL, hla_b INT NOT NULL, hla_cw INT NOT NULL, hla_dr INT NOT NULL, hla_dq INT NOT NULL, hla_dp INT NOT NULL, incompatibilites_hla_a INT NOT NULL, incompatibilites_hla_b INT NOT NULL, incompatibilites_hla_cw INT NOT NULL, incompatibilites_hla_dr INT NOT NULL, incompatibilites_hla_dq INT NOT NULL, incompatibilites_hla_dp INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE materiel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sonde_jj BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, first_name VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, num_dossier INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE serologie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, selorogie_cmv BOOLEAN NOT NULL, selorogie_ebv BOOLEAN NOT NULL, selorogie_toxoplasmose BOOLEAN NOT NULL, selorogie_hiv BOOLEAN NOT NULL, selorogie_htvl BOOLEAN NOT NULL, selorogie_syphilis BOOLEAN NOT NULL, selorogie_hcv BOOLEAN NOT NULL, selorogie_ag_hbs BOOLEAN NOT NULL, selorogie_ac_hbs BOOLEAN NOT NULL, selorogie_ac_hbc BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE transfusion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cgr INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE chirurgien');
        $this->addSql('DROP TABLE donneur_m');
        $this->addSql('DROP TABLE donneur_v');
        $this->addSql('DROP TABLE greffe');
        $this->addSql('DROP TABLE groupage_hla');
        $this->addSql('DROP TABLE materiel');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE serologie');
        $this->addSql('DROP TABLE transfusion');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
